# version format
version: 0.0.{build}

# build with VS17
image: Visual Studio 2017

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release
# build Configuration, i.e. Debug, Release, etc.
configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.{version}"
  assembly_file_version: "1.{version}"
  assembly_informational_version: "1.{version}"


before_build:
  - nuget restore Source/EventMaster.sln
build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - SonarScanner.MSBuild.exe begin /k:"EventMaster_SonarCube" /d:sonar.organization="freakinchuck-github" /d:sonar.host.url="https://sonarcloud.io" /d:"sonar.login=%SonarQubeToken%"
  - msbuild "Source/EventMaster.sln"
  - SonarScanner.MSBuild.exe end /d:"sonar.login=%SonarQubeToken%"
#build:
#  project: Source/EventMaster.sln      # path to Visual Studio solution or project

artifacts:
  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: Source\EventMaster\bin\$(configuration)
    name: EventMaster
